# Generated by Django 2.2 on 2019-05-03 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.IntegerField(unique=True)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('descripcionProducto', models.CharField(max_length=500)),
                ('categoriaProducto', models.CharField(choices=[('electro', 'Electrodomesticos'), ('cocina', 'Articulos de Cocina'), ('banio', 'Articulos de Baño'), ('deco', 'Articulos de Decoracion'), ('jardin', 'Articulos de Jardineria')], default='electro', max_length=50)),
                ('precioProducto', models.PositiveIntegerField(default=0)),
                ('cantidadProducto', models.PositiveIntegerField(default=0)),
                ('ofertaProducto', models.BooleanField(default=False)),
                ('descuentoProducto', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
