# Generated by Django 2.2 on 2019-05-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutUsuario', models.CharField(max_length=20)),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('emailUsuario', models.CharField(max_length=100)),
                ('imagenUsuario', models.CharField(max_length=10000)),
                ('rolUsuario', models.CharField(max_length=20)),
                ('passwordUsuario', models.CharField(max_length=50)),
            ],
        ),
    ]
