# Generated by Django 2.2.1 on 2019-05-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MundoFastWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estadoVenta',
            field=models.CharField(default='En Proceso', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='folioVenta',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='subTotal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
