# Generated by Django 2.2.2 on 2019-07-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MundoFastWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(default='Imagen-no-disponible.png', upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='descripcionEmpresa',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccionEmpresa',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='emailEmpresa',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='horarioEmpresa',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagenEmpresa',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombreEmpresa',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoriaProducto',
            field=models.CharField(choices=[('Electro', 'Electrodomesticos'), ('Cocina', 'Articulos de Cocina'), ('Baño', 'Articulos de Baño'), ('Decoración', 'Articulos de Decoracion'), ('Jardín', 'Articulos de Jardineria'), ('Otros', 'Otros')], default='Electro', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagenUsuario',
            field=models.ImageField(default='Imagen-no-disponible.png', upload_to='usuarios'),
        ),
    ]
