# Generated by Django 2.2 on 2019-05-23 23:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MundoFastWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadProducto', models.PositiveIntegerField(default=1)),
                ('descuentoAplicadoProducto', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('totalPorProducto', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MundoFastWebApp.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVenta', models.DateTimeField(auto_now_add=True)),
                ('cuotasVenta', models.PositiveIntegerField(default=1)),
                ('totalVenta', models.PositiveIntegerField()),
                ('descuendoAdicionalVenta', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('productos', models.ManyToManyField(through='MundoFastWebApp.DetalleVenta', to='MundoFastWebApp.Producto')),
                ('responsableVenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MundoFastWebApp.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MundoFastWebApp.Venta'),
        ),
    ]
