# Generated by Django 2.2.1 on 2019-05-06 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MundoFastWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoriaProducto',
            field=models.CharField(choices=[('Electro', 'Electrodomesticos'), ('Cocina', 'Articulos de Cocina'), ('Baño', 'Articulos de Baño'), ('Decoración', 'Articulos de Decoracion'), ('Jardín', 'Articulos de Jardineria')], default='Electro', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuentoProducto',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
