# Generated by Django 2.2.2 on 2019-07-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MundoFastWebApp', '0002_auto_20190720_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoriaProducto',
            field=models.CharField(choices=[('Electrodomésticos', 'Electrodomésticos'), ('Cocina', 'Artículos de Cocina'), ('Baño', 'Artículos de Baño'), ('Decoración', 'Artículos de Decoracion'), ('Jardín', 'Artículos de Jardineria'), ('Otros', 'Otros')], default='Electrodomésticos', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rolUsuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Desarrollador', 'Desarrollador'), ('Empleado', 'Empleado'), ('Cajero', 'Cajero'), ('Cliente', 'Cliente'), ('Otro', 'Otro')], default='Empleado', max_length=50),
        ),
    ]
