# Generated by Django 2.2 on 2019-06-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MundoFastWebApp', '0002_auto_20190603_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
