# Generated by Django 2.2.2 on 2019-06-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MundoFastWebApp', '0003_auto_20190603_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(max_length=30)),
                ('emailEmpresa', models.CharField(max_length=1000)),
                ('descripcionEmpresa', models.CharField(max_length=10000)),
                ('imagenEmpresa', models.CharField(max_length=10000)),
                ('direccionEmpresa', models.CharField(max_length=50)),
                ('horarioEmpresa', models.CharField(max_length=500)),
            ],
        ),
    ]
