# Generated by Django 2.2.2 on 2019-07-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MundoFastWebApp', '0003_auto_20190720_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rolUsuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Desarrollador', 'Desarrollador'), ('Empleado', 'Empleado'), ('Cajero', 'Cajero'), ('Cliente', 'Cliente'), ('Otro', 'Otro')], default='Desarrollador', max_length=50),
        ),
    ]
