# Generated by Django 2.2.1 on 2019-05-06 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MundoFastWebApp', '0004_auto_20190506_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descuentoProducto',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
